### PR TITLE
22.3 fb finance update

### PR DESCRIPTION
**Pull request by jonesgaohsu**
#### Rationale
Update of XML for public Rate Sheets and addition of PART Spreadsheet and change of filter for other Items

#### Related Pull Requests
* 

#### Changes
*

### CODE REVIEW

**Review by kollil — APPROVED** [review]
Looks good

**Comment by labkey-jeckels** [comment]
@jonesgaohsu you have two different versions of onprc_billing/resources/queries/onprc_billing/publicInvoicedItems.sql in this PR and your other PR, https://github.com/LabKey/onprcEHRModules/pull/435

Which is the final version that you want to be included?

https://github.com/LabKey/onprcEHRModules/blob/22.3_fb_FinancePublicFix/onprc_billing/resources/queries/onprc_billing/publicInvoicedItems.sql

https://github.com/LabKey/onprcEHRModules/blob/22.3_fb_FinanceUpdate/onprc_billing/resources/queries/onprc_billing/publicInvoicedItems.sql

**Comment by labkey-jeckels** [comment]
@jonesgaohsu we recommend against merging this PR. Marty noticed that the ETL won't work because its destination is a linked schema (which can be an ETL source but not destination). Marty also says that the version of publicInvoiceItems.sql in https://github.com/LabKey/onprcEHRModules/pull/435 looks as he'd expect, and the other two files here only have comments.

**Comment by jonesgaohsu** [comment]
Updated the xml for each of the Rate Sheets to correctly show labels for each billing period

**Comment by labkey-martyp** [comment]
@jonesgaohsu @oregonjonesga @kollil As we talked about in our previous meetings, please review the Files Changed tab for this PR when reviewing and before merging.  There are some files currently in here I don't think you want to merge in.

**Comment by jonesgaohsu** [comment]
Update was verified in Test instance and being submitted for 22.3 build

**Pull request merged**
