### PR TITLE
20.11 fb override bcs weight duration

### PR DESCRIPTION
**Pull request by jonesgaohsu**
#### Rationale
THe daily error log was reporting each day that the duration of the BCS weight was changed.  THis is an excepted behavior and should not generate an error

#### Related Pull Requests
* 

#### Changes
CHange to line 36 of BCSScoreWeight demographics

### CODE REVIEW

**Comment by jonesgaohsu** [comment]
Completed Testing no errors, worked as desired

**Comment by labkey-jeckels** [comment]
The BCS weight change looks good. Did you intend to include the change to ONPRC_EHR_ComplianceDB/resources/queries/EHR_ComplianceDB/Measles45DayAlert.sql? I think we talked about this change before and it might be an accident:

https://github.com/LabKey/onprcEHRModules/pull/99/commits/a57414f4a93d899cc8dc6d32787c92f499905093?diff=unified&w=1

**Review by labkey-jeckels — APPROVED** [review]
I pushed a change to revert the query edit

**Comment by jonesgaohsu** [comment]
Artifacts tested and no issues found

**Pull request merged**
