### PR TITLE
Reverting ASB service req form changes

### PR DESCRIPTION
**Pull request by kollil**
#### Rationale
Reverting the ASB form validation code.

### CODE REVIEW

**Review by Ohsudev — APPROVED** [review]

**Review by labkey-jeckels — APPROVED** [review]
From what you've described, this pull request should address the problem users are experiencing in production right now.

However, note that the original feature branch looks like it probably included other changes you didn't intend to commit and will require follow up attention in 21.7. They include:

Removing a large number of "prima" tables from onprc_ehr.xml, which is causing test failures in TeamCity now (but perhaps not real-world problems): 

https://github.com/LabKey/onprcEHRModules/commit/ad04b348d1e4f785263d8a38f360d02c9d8f2e1c#diff-65192522708051015a2aef7ff21d1993f84e0b120561334e3b481e72d1906b79L1067

Commenting out the BiopsyHistologyDataSource in ONPRC_EHRModule.java, which is also causing an automated test failure because it expects that to be an option in the Clinical History list:

https://github.com/LabKey/onprcEHRModules/commit/ad04b348d1e4f785263d8a38f360d02c9d8f2e1c#diff-3aeb88ba512ca419259d5ed7912e91e3af6ac04048a139cba8dc9cd1c5e229f5L616

Changing button text from "Create PMIC Task From Selected" to "Create Task From Selected":

https://github.com/LabKey/onprcEHRModules/commit/ad04b348d1e4f785263d8a38f360d02c9d8f2e1c#diff-3aeb88ba512ca419259d5ed7912e91e3af6ac04048a139cba8dc9cd1c5e229f5L574

**Comment by kollil** [comment]
Josh, 
The current prod version of onprc_ehr.xml is the good one with no Prima tables. 

As you know I didn’t revert any changes. Instead of reverting using GIT commands, I created a new fb (20.11_fb_Revert_ASB) and commented out the code in the two .js files and successfully deployed into UAT.
The changes are tested well in UAT and can be merged into 21.7. 

If we are not touching the branch 20.11_fb_ASB_SpeIns,  How do I clear the Prima tables conflict? I am little confused, sorry ☹

**Comment by labkey-jeckels** [comment]
The problem isn't with this FB to revert the JavaScript code, the problem is with the original pull request that I believe included more changes than you wanted.

The prima tables exist in the production server. Thus, the FB you merged last week shouldn't have removed them from the onprc_ehr.xml file.

As I said, it's OK to sort this out post-upgrade. My guess is that there were merge conflicts between your long-running feature branch (you mentioned it was from June) that were incorrectly resolved.

**Comment by kollil** [comment]
Thanks Josh. I suspect the same. We can figure this out post-upgrade.

**Pull request merged**
