### PR TITLE
Created an etl process to move data from temp table into

### PR DESCRIPTION
**Pull request by Ohsudev**
#### Changes
Created an etl process to move data from temp table into
study.antibioticsensitivity table.

### CODE REVIEW

**Review by kollil — COMMENTED** [review]
Looks good, Raymond. Is the cron job scheduling part missing?

**Review by kollil — APPROVED** [review]

**Comment by Ohsudev** [comment]
This etl project won’t be a scheduled run. Will be running this etl only when needed.

Thanks,
Raymond

From: Lakshmi Kolli ***@***.***>
Sent: Wednesday, July 28, 2021 1:15 PM
To: LabKey/onprcEHRModules ***@***.***>
Cc: Raymond Blasa ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [LabKey/onprcEHRModules] Created an etl process to move data from temp table into (#222)


@kollil commented on this pull request.

Looks good, Raymond. Is the cron job scheduling part missing?

**Comment by Ohsudev** [comment]
Hi Josh.  Can you please review this feature branch.  I have a separate sql stored procedure that will generate records into a temp table, and will require just this etl process to execute and copy data from temp table into Prime dataset.

This will not be a scheduled etl process, since I will be processing legacy records six month's entries at a time.

**Review by labkey-jeckels — APPROVED** [review]
Looks fine to me.

**Pull request closed without merging**
