### PR TITLE
21.7 fb hansen queryto file xml

### PR DESCRIPTION
**Pull request by jonesgaohsu**
#### Rationale
ETL FIles to run queries for Hansen Lab and export to file structure for retrrieval

#### Related Pull Requests
* 

#### Changes
*

### CODE REVIEW

**Comment by jonesgaohsu** [comment]
Added new dataset that was not present in test1 instance

**Review by kollil — APPROVED** [review]
Looks good.

**Comment by jonesgaohsu** [comment]
Commitgting to Default for Update of processes related to Randal Build

**Comment by labkey-jeckels** [comment]
@jonesgaohsu this change is causing tests to fail because the new table, studydetails_randaldata, isn't included in onprc_ehr.xml. Can you please add it in a followup feature branch and pull review?

**Comment by jonesgadev** [comment]
Will make then addition

**Pull request merged**
