### PR TITLE
Modified program so that only Biopsy Diagnosis entries are reported.

### PR DESCRIPTION
**Pull request by Ohsudev**
#### Changes
Modified program so that only Biopsy Diagnosis entries are reported.

### CODE REVIEW

**Review by kollil — APPROVED** [review]

**Review by labkey-jeckels — CHANGES_REQUESTED** [review]
These changes look fine, but you'll see that there's an automated test failure. If you click to look at the error, you'll see that it's complaining that the list of clinical history options doesn't match the expected list. This snuck in with your recent Biopsy change:

https://teamcity.labkey.org/viewModification.html?modId=423126&personal=false&tab=vcsModificationFiles&buildTypeId=LabKey_2011Release_Premium_Ehr_DailyEhrSqlserver

It's a good candidate for you to update the test so that it's expecting the new Biopsy option.

The code is here:

https://github.com/LabKey/ehrModules/blob/release20.11-SNAPSHOT/ehr/test/src/org/labkey/test/tests/onprc_ehr/ONPRC_EHRTest.java#L1758

 You'll want to add the new entry to the list. Then create a feature branch in the ehrModules repo with the same name as the current onprcEHRModules FB, 20.11_fb_BiopsyDiagnosisUpdate.

Commit and push the changes, then go to TeamCity to trigger a new build by clicking Run (it's automatically triggering on changes to the onprcEHRModules repo, but not ehrModules).

https://teamcity.labkey.org/buildConfiguration/LabKey_2011Release_Premium_Ehr_OnprcEhrSqlserver/1446088

Let us know if you hit snags or have questions.

**Comment by Ohsudev** [comment]
Hi Josh.  I made the program changes as you suggested.  Can you please review both ehr and onprcehr modules.  Tested the feature branch that includes the changes on ehr, and seems to work fine.

**Review by labkey-jeckels — APPROVED** [review]
I didn't see a new test run on TeamCity after your ehrModules update so I manually triggered one. It just finished, and the test update worked.

https://teamcity.labkey.org/buildConfiguration/LabKey_2011Release_Premium_Ehr_OnprcEhrSqlserver/1447069

Please go ahead and merge both PRs at the same time.

https://github.com/LabKey/ehrModules/pull/196

**Comment by Ohsudev** [comment]
Thank you.  I “squash and Merge” #196, and then #186.  Hopefully, I did this process correctly for final default branch.

Thanks,
Raymond

From: Josh Eckels ***@***.***>
Sent: Wednesday, June 16, 2021 9:57 PM
To: LabKey/onprcEHRModules ***@***.***>
Cc: Raymond Blasa ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [LabKey/onprcEHRModules] Modified program so that only Biopsy Diagnosis entries are reported. (#186)


@labkey-jeckels approved this pull request.

I didn't see a new test run on TeamCity after your ehrModules update so I manually triggered one. It just finished, and the test update worked.

https://teamcity.labkey.org/buildConfiguration/LabKey_2011Release_Premium_Ehr_OnprcEhrSqlserver/1447069

Please go ahead and merge both PRs at the same time.

LabKey/ehrModules#196<https://github.com/LabKey/ehrModules/pull/196>

**Comment by labkey-jeckels** [comment]
@Ohsudev yes, your merges look good. There's no trick to merging multiple PRs together. It's just a matter of clicking the squash and merge button for both without a delay between them.

Congrats on making the test fix. Now we can be confident that your work to include biopsies continues to show up as an option in Clinical History.

**Pull request merged**
