### PR TITLE
Restored the Weights by Monkey Id from the Printable reports that was…

### PR DESCRIPTION
**Pull request by Ohsudev**
… inadvertently removed from the web page.

#### Changes
Restored the Weights by Monkey Id from the Printable reports that was inadvertently removed from the web page.

### CODE REVIEW

**Review by kollil — APPROVED** [review]

**Comment by labkey-jeckels** [comment]
@Ohsudev your change looks fine. You'll see what I pushed a separate change to get the automated tests passing again - they've been broken for a little while from some unrelated changes.

Going forward, I'm going to be strict on making sure that PRs don't introduce new failures. @keith-labkey let's put this on the agenda for our next weekly call.

**Review by labkey-jeckels — APPROVED** [review]
There was an intermittent test failure during the most recent run, but the failure related to missing columns in the PMIC_CTImagingData dataset is resolved. Please merge at your convenience.

**Comment by labkey-jeckels** [comment]
@Ohsudev Is this ready to merge? We'd like to get the test fix in before we do the 20.11->21.3 merge that we discussed on Tuesday's all.

@labkey-tchad This fixes the failure that you noticed in 20.11.

**Comment by Ohsudev** [comment]
Yes, please proceed, and merge this feature branch.

Thanks,
Raymond

From: Josh Eckels ***@***.***>
Sent: Friday, June 4, 2021 12:42 PM
To: LabKey/onprcEHRModules ***@***.***>
Cc: Raymond Blasa ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [LabKey/onprcEHRModules] Restored the Weights by Monkey Id from the Printable reports that was… (#171)


@Ohsudev<https://github.com/Ohsudev> Is this ready to merge? We'd like to get the test fix in before we do the 20.11->21.3 merge that we discussed on Tuesday's all.

@labkey-tchad<https://github.com/labkey-tchad> This fixes the failure that you noticed in 20.11.

**Pull request merged**
