### PR TITLE
Support pipeline job to aggregate MHC data prior to ETL

### PR DESCRIPTION
**Pull request by labkey-jeckels**
#### Rationale
We're looking to ETL MHC data from prime-seq to the EHR on prime

#### Related Pull Requests
* https://github.com/LabKey/onprcEHRModules/pull/181

### CODE REVIEW

**Review by bbimber — APPROVED** [review]

**Comment by bbimber** [comment]
@labkey-jeckels seems like that test failure is likely not related?

**Comment by labkey-jeckels** [comment]
I spent a while chasing this down. Yes, unrelated to the intended change itself. The FB wasn't current with all of the other changes in release21.3-SNAPSHOT, so it was missing the semi-newly added validation that the test was expecting. I don't know if this was a problem in your original FB on your fork, or when I moved it to the LK repo.

https://github.com/LabKey/onprcEHRModules/commits/release21.3-SNAPSHOT

https://github.com/LabKey/onprcEHRModules/commits/21.3_fb_mhc

The April 29 change is what added the validation.

**Comment by bbimber** [comment]
Thanks - it's possible i got that wrong, but i really thought i was basing off the proper labkey/release21.3-SNAPSHOT.

@labkey-tchad Would it be possible to confirm which onprcEHR branch these builds pull from: https://teamcity.labkey.org/project/LabKey_213Release_External_Discvr?mode=builds? I thought it was release21.3-SNAPSHOT, but these changes dont seem to be getting picked up.

**Comment by labkey-jeckels** [comment]
I think the problem was that your repo's fork of the release21.3-SNAPSHOT branch isn't current with the latest changes in our repo. Thus, you probably started from the right branch, but it was missing recent commits, including the one that added the validation the test was checking for:

https://github.com/bbimber/onprcEHRModules/commits/release21.3-SNAPSHOT

**Comment by bbimber** [comment]
ok, my bad. on the other branches i have a GH action to keep my fork in sync, but i work here so sporadically.  i will watch that.

**Comment by bbimber** [comment]
On TeamCity: I think perhaps the issue is that the DISCVR team city project builds from my repos, but when it creates the prime-seq distribution, it pulls onprcEHR from artifactory? That's the only thing I can figure out, since I dont see "ONPRC" in the build log:

https://teamcity.labkey.org/buildConfiguration/LabKey_213Release_External_Discvr_Installers/1447823?buildTab=log&focusLine=3

This seem right? Does the artifactory version of onprcEHRModules/GeneticsCore module update nightly when changes are merged?

**Pull request merged**
