### PR TITLE
Refactor kinship to allow other code to initiate import directly

### PR DESCRIPTION
**Pull request by bbimber**

### CODE REVIEW

**Comment by bbimber** [comment]
@jonesgaohsu: this is a rework of the earlier PR here: https://github.com/LabKey/onprcEHRModules/pull/782, now targeting 23.11. would you mind approving?

**Comment by jonesgaohsu** [comment]
Marty can you process this to Team City for testing.  I have a non prod instance of 23.11 I can test against

**Comment by jonesgaohsu** [comment]
Compiled and loaded onto primesandbox.ohsu.edu which is a 23.11 build no errors were found

**Comment by bbimber** [comment]
@jonesgaohsu: can you please formally approve this, so we can merge? there should be UI right below this post

**Comment by jonesgaohsu** [comment]
build verified one test instance

**Review by jonesgaohsu — APPROVED** [review]
No iSsue found

**Pull request merged**
