### PR TITLE
20.11 fb e iacucetl

### PR DESCRIPTION
**Pull request by jonesgaohsu**
#### Rationale
ETL to insert data from external schema to files within ONPRC_EHR

#### Related Pull Requests
* 

#### Changes
*

### CODE REVIEW

**Comment by jonesgaohsu** [comment]
Tested on Test 1 instance and ran without error, ready to merge and squash to Production

**Comment by jonesgaohsu** [comment]
Corrected the merge to 20.11 from 20.12 and ready for deployment

**Comment by jonesgaohsu** [comment]
Is there a reason this lacks approval?

**Review by kollil — APPROVED** [review]
Looks good!

**Comment by jonesgaohsu** [comment]
Commited for reploy to production

**Pull request merged**
