### PR TITLE
Customized procedures - Spe Ins field for ASB service req form

### PR DESCRIPTION
**Pull request by kollil**
#### Rationale
Changed the Procedures -> Special Instructions field to be a drop down list on ASB service req form. The rest of the places it's a text area.

### CODE REVIEW

**Review by Ohsudev — APPROVED** [review]
Looks good.

**Comment by kollil** [comment]
Thank you Raymond.

**Review by labkey-jeckels — APPROVED** [review]
Code looks fine and tests are passing.

**Comment by labkey-jeckels** [comment]
@kollil did you intend to merge changes from the 20.11_fb_ExtSchCovidDBScripts branch into this feature branch? They don't seem related.

**Comment by kollil** [comment]
@labkey-jeckels,  
Me and Gary were trying to test something to solve the issue of overwriting each other's work. When I deployed my fb this morning it removed some of his extScheduler stuff. So, I merged Gary's fb into my fb and made modifications to one file in my fb and committed that change, we noticed in the installer it picked up Gary's fb too. We are waiting to see when I deploy this fb into prime20test, it should pick up his stuff and mine.

**Comment by labkey-jeckels** [comment]
@kollil OK, very good. Since that merge has a significant impact on the changes that are part of this pull request, I suggest that you request an additional review after your testing and before you merge it.

**Comment by kollil** [comment]
@labkey-jeckels , Team city couldn't collect my latest changes and the build failed. Could you please let me know if I did anything wrong? Do I need to commit the changes again?

Thanks
Lakshmi

**Comment by labkey-jeckels** [comment]
You didn't do anything wrong. We intermittently get these errors from GitHub around 6PM when TeamCity is kicking off lots of nightly builds and tests.

I manually clicked Run to get TeamCity to spin another build on this branch:

https://teamcity.labkey.org/buildConfiguration/LabKey_2011Release_External_Onprc_OnprcInstaller/1445776

**Pull request merged**
