### PR TITLE
Update of Notification Java file to use labkeyPublic for review

### PR DESCRIPTION
**Pull request by jonesgaohsu**
#### Rationale
Updatge was completed with new query loaded

#### Related Pull Requests
* 

#### Changes
ValidateAvailableBloodProcess.sql

### CODE REVIEW

**Review by kollil — APPROVED** [review]

**Review by brentlogan — CHANGES_REQUESTED** [review]
Gary, in my daily review of our VMs, I see that sandbox is throwing an HTTP 500 error. Who knew that a misconfigured cron would prevent LabKey from working?! Anyways, I reviewed your code and see no space after the hour range. Here are my recommendations:

-  Line 51

`return "0 30 7-18 * * ?";`

- Line 57

`return "every day at 30 minutes after the hour between 7:30AM and 6:30PM";`

This matches the style of other schedules on https://prime.ohsu.edu/ldk/ONPRC/EHR/notificationAdmin.view?

- Continue to get code reviews for **_all_** changes, even simple ones, after the initial code review. I recommend meeting with the reviewer so the code can be discussed. The recommended changes can still be captured in GitHub for posterity.

**Review by jonesgaohsu — COMMENTED** [review]
inserted the needed space and code now passes in development

**Comment by jonesgaohsu** [comment]
Changes suggested by Brent have been included int this push

**Review by jonesgaohsu — COMMENTED** [review]
after response from Brent made additional Modifications to the file and submitted

**Comment by jonesgaohsu** [comment]
Inspection of result set showed failure and required modification and testing of base query ValidateAvailableBloodProcess.sql.  Tested on Development and get expected dataset return

**Comment by jonesgaohsu** [comment]
All suggested changes were made and reviewed by Brent

**Review by jonesgaohsu — COMMENTED** [review]
Requested changesx are in place

**Review by brentlogan — CHANGES_REQUESTED** [review]
I propose the following for ValidateAvailableBloodProcess.sql:

```
/* Returns a single row of data where the date/hour of the Mathematica ABV calculations don't match the current date or hour.
 * If there is Mathematica data from multiple hours, there will be a row of data for each hour of Mathematica data. 
 * This is not expected as Mathematica should drop the _public table each hour and the ETL'd data should match.
 */
SELECT DISTINCT CAST(a.dateCreated AS DATE) AS mmaDate,
	hour(a.datecreated) AS mmaHour,
	curdate() AS currentDate,
	hour(now()) AS currentHour
FROM ONPRC_EHR.AvailableBloodVolume AS a
WHERE hour(a.dateCreated) != hour(now())
	OR CAST(a.dateCreated AS DATE) != curdate()
```

**Review by jonesgaohsu — COMMENTED** [review]
Change makes good sense and was tested on Dev with no issue

**Comment by jonesgaohsu** [comment]
Latest build is loaded on sandbox

**Review by brentlogan — COMMENTED** [review]
I request you to make 2 changes:

1. Delete the comma at the end of line 8 of onprc_ehr/resources/queries/onprc_ehr/ValidateAvailableBloodProcess.sql
2. Delete the word "daily" near the end of line 53 of onprc_ehr/src/org/labkey/onprc_ehr/notification/AvailableBloodVolumeNotification.java. Make sure not to delete the quotes and semicolon.
Thanks!

**Comment by jonesgaohsu** [comment]
Updates requested have been merged and the files are up to date with latest Production Build

**Review by brentlogan — APPROVED** [review]
Looks good. I corrected a few capitalization issues and a typo.

**Pull request merged**
