### PR TITLE
Add remote deleteRowsSource to MHC ETL

### PR DESCRIPTION
**Pull request by bbimber**

### CODE REVIEW

**Comment by bbimber** [comment]
@kollil or @labkey-martyp: what's the process at this point for getting changes into ONPRC_EHR?

**Comment by labkey-martyp** [comment]
> @kollil or @labkey-martyp: what's the process at this point for getting changes into ONPRC_EHR?

@bbimber, Production is on 22.7 and last I heard there would not be an upgrade to a new version until this summer. I believe if you want to get this on production sooner you'll want to target 22.7 and coordinate with @jonesgaohsu and Brent for when the next 22.7 snapshot will be installed.

**Comment by bbimber** [comment]
@labkey-martyp: yeah, i figured that. it doesnt do any good to deploy this XML on any server that isnt running 23.3 though. 23.3 is the right target.

**Comment by labkey-martyp** [comment]
> @labkey-martyp: yeah, i figured that. it doesnt do any good to deploy this XML on any server that isnt running 23.3 though. 23.3 is the right target.

@bbimber Right I forgot what version we got that change into. Has to be 23.3 or later.

**Comment by bbimber** [comment]
@labkey-martyp: ok, so how's approval work in this repo?

**Comment by labkey-martyp** [comment]
> @labkey-martyp: ok, so how's approval work in this repo?

The ONPRC team handles the PR approvals in this repo. On the LK side we only review PRs here if we're asked to or if we see something that could be problematic. So I would recommend pinging the ONPRC team first and on the LK side we're happy to follow up if there are questions.

**Comment by bbimber** [comment]
OK. @Ohsudev or @jonesgaohsu: would it be possible to approve this PR?

**Review by jonesgaohsu — APPROVED** [review]
Review of changes and this has been tested on a test instance and was functional

**Pull request merged**
