### PR TITLE
Fire formulary actions when a template is populating the form

### PR DESCRIPTION
**Pull request by labkey-jeckels**
#### Rationale
ONPRC_EHRTest.testExamEntry started failing with recent changes to the formulary code, noticing that the formulary wasn't being applied when a template populated a row

#### Related Pull Requests
* https://github.com/LabKey/onprcEHRModules/pull/86

#### Changes
* When adding a new row make sure the formulary code fires too

### CODE REVIEW

**Comment by labkey-jeckels** [comment]
@Ohsudev Raymond can you verify that this change doesn't break your intended change? I think it should be fine and make the templates work again but you know more about the desired behavior.

**Comment by Ohsudev** [comment]
Thanks Josh.  I will test your code changes again for you.

Raymond

**Comment by Ohsudev** [comment]
I tested the program changes made, and had the program reviewed by a DCM manager.  She confirmed program changes you made was working just fine.

**Comment by labkey-jeckels** [comment]
Thanks Raymond! @Ohsudev

**Review by labkey-sweta — APPROVED** [review]

**Pull request merged**
