### PR TITLE
21.7 fb update title length

### PR DESCRIPTION
**Pull request by jonesgaohsu**
#### Rationale
The title field of Protocol was limited to 80 characters which did not allow the full title of a Protocol to be listed.  the NIH Standard for Protocol Titles is 200 characters

#### Related Pull Requests
* 

#### Changes
Updated onprc_ERHCustomizer lie1554 by setting scale to 200

### CODE REVIEW

**Review by labkey-jeckels — CHANGES_REQUESTED** [review]
The code change looks fine, but as the GitHub automated review pointed out, the feature branch has a typo in its name so TeamCity won't fire installer builds and tests. Can you recreate with the right name?

**Comment by jonesgaohsu** [comment]
I miss named the feature branch and have corrected the issue

**Comment by jonesgaohsu** [comment]
should I cancel this feature branch I did correc the naming and pushed

**Comment by jonesgaohsu** [comment]
Closing this request since the naming was incorr3ect and renaming here dod not trigger team city. will submit a new FB with correc naming

**Pull request closed without merging**
