### PR TITLE
Art core fix

### PR DESCRIPTION
**Pull request by kollil**
Updated the container path with substitute property.

### CODE REVIEW

**Review by Ohsudev — APPROVED** [review]

**Review by labkey-jeckels — CHANGES_REQUESTED** [review]
@kollil this feature branch reintroduces the ehrSLA.xml file that caused many problems and I removed in my separate PR yesterday. Did you intentionally recreate it? It's broken all of the tests again in this feature branch.

**Comment by kollil** [comment]
@labkey-jeckels , I pushed the ART core fix with the correct path, but the ehrsla.xml got into the PR without me doing anything. I am confused why it was included as it was safely deleted from my dev env last week. I am attaching the snapshot of the commit process here. I hope the test scripts failed again because of this. Please let me know if I need to do anything from my side.
SLA_push

**Comment by labkey-jeckels** [comment]
@kollil your screenshot shows that ehrSLA.xml has indeed been deleted locally on your dev machine, but you haven't committed or pushed that change into Git. That's why it's showing in the Commit pane's tree of files in gray.

Just like with adding or editing files, you need to commit and push deletes to make your feature branch in GitHub match what you have locally.

**Review by labkey-jeckels — APPROVED** [review]
This change fixes the problem with ARTCoreBillingCharges. That's good, though there are still other query validation errors. But you're clear to merge this PR as it gets us closer to passing the tests again.

**Comment by labkey-jeckels** [comment]
I'm going to merge this change to get the tests closer to passing.

**Pull request merged**
