### PR TITLE
Created a new program that will export data from temp table into exte…

### PR DESCRIPTION
**Pull request by Ohsudev**
…rnal csv file.  After the program creates csv file, resets the temp table for the next set of data.

#### Changes

Created a new program that will export data from temp table into external csv file.  After the program creates csv file, resets the temp table for the next set of data.

### CODE REVIEW

**Comment by labkey-jeckels** [comment]
@Ohsudev does this ETL run without errors? I've never seen or tried one without a <source> for each step and I'd expect it to fail. I don't think I have the LIS.PrimeHarvestFinal set up locally so I can't easily test myself.

If it doesn't run as-is, you could create a dummy query that does a "SELECT NULL AS X WHERE 1=0" or something similar to act as a source that will produce no rows.

**Comment by Ohsudev** [comment]
I will test again to be sure it is working.

Thanks,
Raymond

From: Josh Eckels ***@***.***>
Sent: Friday, April 2, 2021 5:02 PM
To: LabKey/onprcEHRModules ***@***.***>
Cc: Raymond Blasa ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [LabKey/onprcEHRModules] Created a new program that will export data from temp table into exte… (#137)


@Ohsudev<https://github.com/Ohsudev> does this ETL run without errors? I've never seen or tried one without a for each step and I'd expect it to fail. I don't think I have the LIS.PrimeHarvestFinal set up locally so I can't easily test myself.

If it doesn't run as-is, you could create a dummy query that does a "SELECT NULL AS X WHERE 1=0" or something similar to act as a source that will produce no rows.

**Comment by Ohsudev** [comment]
I wanted to create a feature branch build so that I can test the program on Prime 20 test, or Prime UAT since my local
Development intellij by default isn’t connected to external schema data set.

Is it safe to activate the external schemas settings on my development box?

Thanks,
Raymond

From: Josh Eckels ***@***.***>
Sent: Friday, April 2, 2021 5:02 PM
To: LabKey/onprcEHRModules ***@***.***>
Cc: Raymond Blasa ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [LabKey/onprcEHRModules] Created a new program that will export data from temp table into exte… (#137)


@Ohsudev<https://github.com/Ohsudev> does this ETL run without errors? I've never seen or tried one without a for each step and I'd expect it to fail. I don't think I have the LIS.PrimeHarvestFinal set up locally so I can't easily test myself.

If it doesn't run as-is, you could create a dummy query that does a "SELECT NULL AS X WHERE 1=0" or something similar to act as a source that will produce no rows.

**Comment by labkey-jeckels** [comment]
You've got the feature branch already so you can certainly test out the change as-is on UAT or Test.

If all you're doing is read-only queries against the source schema it should be safe to set up the external schema database connection on your dev machine. But of course the DBAs may want to control how many servers are connecting or how the credentials are shared, so I'd double-check with them.

**Comment by Ohsudev** [comment]
Thank you.  The only functionality to this new etl that I’m interested in determining  can the program be
able to copy data from a data set from Prime into an external network folder.

I’m using ehr_lookups.areas as a source test data set since it has only a few rows in it on my dev box.

Thanks,
Raymond

From: Josh Eckels ***@***.***>
Sent: Friday, April 2, 2021 6:09 PM
To: LabKey/onprcEHRModules ***@***.***>
Cc: Raymond Blasa ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [LabKey/onprcEHRModules] Created a new program that will export data from temp table into exte… (#137)


You've got the feature branch already so you can certainly test out the change as-is on UAT or Test.

If all you're doing is read-only queries against the source schema it should be safe to set up the external schema database connection on your dev machine. But of course the DBAs may want to control how many servers are connecting or how the credentials are shared, so I'd double-check with them.

**Comment by Ohsudev** [comment]
The testing of the  etl ran fine, but the program did not create an output file to a network folder.  Was the output file actually created, or Prime
cannot create a file on a network folder?

Thanks,
Raymond

From: Josh Eckels ***@***.***>
Sent: Friday, April 2, 2021 6:09 PM
To: LabKey/onprcEHRModules ***@***.***>
Cc: Raymond Blasa ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [LabKey/onprcEHRModules] Created a new program that will export data from temp table into exte… (#137)


You've got the feaTheture branch already so you can certainly test out the change as-is on UAT or Test.

If all you're doing is read-only queries against the source schema it should be safe to set up the external schema database connection on your dev machine. But of course the DBAs may want to control how many servers are connecting or how the credentials are shared, so I'd double-check with them.

**Comment by labkey-jeckels** [comment]
UAT, test, and production servers are all running on Linux. The path you've specified looks like a Windows-style path:

\\primateapp3\HarvestData\PrimeToHarvest

The file system will need to be mounted as a Linux file system, perhaps via an addition to the fstab mapping on the servers, in order for it to be available for writing or reading files.

**Comment by Ohsudev** [comment]
Thank you, Josh. I will check with Acc if it is possible for them to do that for me.

The information you provided was very helpful.

I want you to know we always appreciated all the assistance you have provided us past and present through these years.

Thanks,
Raymond
________________________________
From: Josh Eckels ***@***.***>
Sent: Saturday, April 3, 2021 12:21:00 PM
To: LabKey/onprcEHRModules
Cc: Raymond Blasa; Mention
Subject: [EXTERNAL] Re: [LabKey/onprcEHRModules] Created a new program that will export data from temp table into exte… (#137)


UAT, test, and production servers are all running on Linux. The path you've specified looks like a Windows-style path:

\primateapp3\HarvestData\PrimeToHarvest

The file system will need to be mounted as a Linux file system, perhaps via an addition to the fstab mapping on the servers, in order for it to be available for writing or reading files.

**Comment by labkey-jeckels** [comment]
Thanks Raymond! It's been great seeing you and the rest of the team tackle and deliver more and more ambitious projects over the years.

**Comment by Ohsudev** [comment]
No longer needed.

**Pull request closed without merging**
