### PR TITLE
Modified to include vet control listings into both Labwork request an…

### PR DESCRIPTION
**Pull request by Ohsudev**
…d labwork form type.

#### Changes
Modified to include vet control listings into both Labwork request and labwork form type.

### CODE REVIEW

**Review by labkey-jeckels — APPROVED** [review]

**Comment by Ohsudev** [comment]
Hi Josh. I made new changes to this feature branch since you reviewed it last.  Can you please review this feature branch again.

**Comment by labkey-jeckels** [comment]
@Ohsudev I only see one commit with the edits to onprc_ehr/resources/web/onprc_ehr/model/sources/labworkPanel.js in this pull request. Can you double-check that you pushed the subsequent updates?

**Comment by Ohsudev** [comment]
Sorry, Josh.  The last commit for you need to review didn’t go through because of the following statement into
Intellij.
Warning:(1, 1) No data sources are configured to run this SQL and provide advanced code assistance.

The program ran fine without errors by executing my sql statement within the schema browser “Create New query” interface.

I will submit this to Chet for him assist me to this issue.

Thanks,
Raymond

From: Josh Eckels ***@***.***>
Sent: Monday, April 5, 2021 2:16 PM
To: LabKey/onprcEHRModules ***@***.***>
Cc: Raymond Blasa ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [LabKey/onprcEHRModules] Modified to include vet control listings into both Labwork request an… (#121)


@Ohsudev<https://github.com/Ohsudev> I only see one commit with the edits to onprc_ehr/resources/web/onprc_ehr/model/sources/labworkPanel.js in this pull request. Can you double-check that you pushed the subsequent updates?

**Comment by Ohsudev** [comment]
Recreating a new pull request.

**Pull request closed without merging**
