### PR TITLE
21.7 fb sla usage

### PR DESCRIPTION
**Pull request by kollil**
Fixed the breeding info

### CODE REVIEW

**Review by Ohsudev — APPROVED** [review]

**Comment by kollil** [comment]
@labkey-jeckels, 
After creating the default branch (#92,  I discovered a bug and committed the file, sla/resources/queries/sla/allowableAnimals_BreedingGroups.sql into the same branch. Please approve the changes.

**Review by labkey-jeckels — CHANGES_REQUESTED** [review]
GitHub is showing that there are conflicts that need to be resolved before this can be merged. You will need to merge the latest changes from release21.7-SNAPSHOT into your feature branch, resolve any conflicts, and push them into the feature branch.

They may have been introduced by not being current with the latest changes from  release21.7-SNAPSHOT before creating your feature branch, and then re-creating the edits that you already merged into release21.7-SNAPSHOT.

Once GitHub shows there are no conflicts I can review/approve.

It's possible that it will be easiest to create a new feature branch (after pulling the latest from release21.7-SNAPSHOT) instead of reconciling the conflicts.

**Comment by kollil** [comment]
@labkey-jeckels, I followed your suggestions, 
Got the latest from master and created a new fb (21.7_fb_SLAGroupsUpdate) and added all the updated files.
Hope this will fix the conflicts.

**Comment by labkey-jeckels** [comment]
I think we can close this PR and delete its FB, since we're moving forward with the other one. Correct?

https://github.com/LabKey/onprcEHRModules/pull/276

**Comment by kollil** [comment]
@labkey-jeckels , Yes, we can close this fb. I will be using PR #276.

**Comment by labkey-jeckels** [comment]
@kollil Great. Please close the PR and delete the corresponding branch. It's easy - use the Close button at the bottom of the Conversation tab. You should then get a button to delete the branch. You can do this with any other pull requests that are no longer relevant. Both you and Raymond have a number of lingering, old pull requests:

https://github.com/LabKey/onprcEHRModules/pulls

**Comment by kollil** [comment]
Closing this fb as a new fb is created for this project.

**Pull request closed without merging**
