### PR TITLE
20.11 fb genetic bloodfor dna

### PR DESCRIPTION
**Pull request by jonesgaohsu**
#### Rationale
Removed a line of code in genetics blood draw for processing to check for gDNA sample in DNA Samples dataset

#### Related Pull Requests
* 

#### Changes
*

### CODE REVIEW

**Review by kollil — APPROVED** [review]
Gary, The genetics code changes look good as per your design changes. Why are the Prima files that were deleted added to this pull?

**Review by labkey-jeckels — CHANGES_REQUESTED** [review]
Lakshmi's comment about the extra files is indeed a problem with the PR that needs to be corrected. See the messages from our automated scripts in the Conversation tab about the target branch that's been selected.

**Comment by jonesgaohsu** [comment]
I have corrected the target branch I missed that when I made the commitment

**Review by labkey-jeckels — COMMENTED** [review]
The branch looks good now.

Note that the comment you added on line 113 isn't actually part of the query - it's commented out on line 115. If that's what you intended, you might want to update or remove the comment.

**Comment by jonesgaohsu** [comment]
Reviewed update of code and unneeded items removed at  line 115

**Comment by jonesgaohsu** [comment]
Josh did the changes come thru correctly?

**Review by labkey-jeckels — APPROVED** [review]
Yes, if you intended to remove the gDNA filter and comment, then yes!

**Pull request merged**
