### PR TITLE
SLA Inv fix

### PR DESCRIPTION
**Pull request by kollil**
Fixing the missing investigator info in the purchase order confirmation form.

### CODE REVIEW

**Review by Ohsudev — APPROVED** [review]

**Comment by labkey-keith** [comment]
@kollil Similar to the other PR, please look into the test failures on this feature branch and do not hesitate to reach out if you need help diagnosing or fixing the errors.

**Comment by kollil** [comment]
@labkey-jeckels, Josh I am not able to merge this fix as the automated tests failed with an exception while attempting to load ehrSLA.xml. First of all, this file was deleted before the upgrade, but it showed up again in this fb and got created without my knowledge. I deleted the file in the other #PR 446 and the default branch was created already. I want to create another default and install this fix too tonight but the tests are stopping me to proceed. How do I solve this issue? I just tried to delete the file again in this fb and re-committed. Is this the right way of fixing this issue?

**Comment by labkey-jeckels** [comment]
@kollil Given the new failures, it's likely that your release22.3-SNAPSHOT branch isn't current, and thus your feature branch didn't include the latest changes. Please try pulling the latest updates for release22.3-SNAPSHOT and merging it into your feature branch.

I see your newer commit that deletes the file. I'm guessing that you may have deleted it locally but not pushed that change yet?

**Comment by kollil** [comment]
> @kollil Given the new failures, it's likely that your release22.3-SNAPSHOT branch isn't current, and thus your feature branch didn't include the latest changes. Please try pulling the latest updates for release22.3-SNAPSHOT and merging it into your feature branch.
> 
> I see your newer commit that deletes the file. I'm guessing that you may have deleted it locally but not pushed that change yet?

@labkey-jeckels,
I updated the fb and there were no new updates. I do remember that ehrSLA was a problem and you pointed out to delete that file before the 22.3 merge and it was clean since then. I did get latest from 22.3, but, something went wrong probably on my end that I cannot identify now. I hope it's fixed now as I deleted the file again, is there anything I need to do so I can merge this fb into the master with no errors?

**Comment by kollil** [comment]
> @labkey-jeckels, Josh I am not able to merge this fix as the automated tests failed with an exception while attempting to load ehrSLA.xml. First of all, this file was deleted before the upgrade, but it showed up again in this fb and got created without my knowledge. I deleted the file in the other #PR 446 and the default branch was created already. I want to create another default and install this fix too tonight but the tests are stopping me to proceed. How do I solve this issue? I just tried to delete the file again in this fb and re-committed. Is this the right way of fixing this issue?

Also, I just checked the tests that failed and they are not related to the changes I made,

https://teamcity.labkey.org/buildConfiguration/LabKey_223Release_Premium_Ehr_OnprcEhrSqlserver/1835509?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildTestsSection=true

How can I fix these?

**Comment by labkey-jeckels** [comment]
Your feature branch is not current with the changes that are part of release22.3-SNAPSHOT. You can compare the commits in each at these URLs:

https://github.com/LabKey/onprcEHRModules/commits/release22.3-SNAPSHOT

https://github.com/LabKey/onprcEHRModules/commits/22.3_fb_SLAInvBugFix

You can see that your FB is missing the commits from May 23 and 25 that fixed the tests. We need to get those into your FB via the update and merge process.

Your FB also includes the May 17 commit that introduced the problematic ehrSLA.xml file.

Gary recently updated a FB with the latest from the main 22.3 branch. I recommend connecting with him to double-check if there's any steps that you may have missed, and if you're still stuck afterwards we can look to connect.

**Comment by labkey-jeckels** [comment]
I added the recommended steps as 8C to the Git documentation here:

https://www.labkey.org/ONPRC/wiki-page.view?name=DevProcess

I also added a note at the very bottom that may help clear out that ehrSLA.xml file for good. Check for the green arrow on the release22.3-SNAPSHOT branch in IntelliJ and follow the steps if you see it.

**Pull request merged**
