### PR TITLE
Fix invalid XML syntax in comment

### PR DESCRIPTION
**Pull request by labkey-jeckels**
#### Rationale
I've seen errors like this:

WARN  ModuleQueryMetadataDef   2021-07-02T17:26:19,759     SearchService:runner : Unable to load meta-data from module query file queries/study/PMIC_encounters.query.xml

It's because the comment at the beginning of the comment isn't well-formed XML

#### Changes
* Fix XML syntax to clear error

### CODE REVIEW

**Comment by labkey-jeckels** [comment]
@kollil I forgot that I opened this pull request last month. I think this file has been mentioned on one of the weekly calls, but the fix hasn't been made in the main release20.11-SNAPSHOT branch. Can you review and approve so we can clear the logging messages?

**Comment by labkey-jeckels** [comment]
@kollil Can you approve this PR so that we can clear out this error? It's continued to log on lots of servers.

**Review by kollil — APPROVED** [review]
Josh, Please review the changes and approve.

**Review by labkey-jeckels — COMMENTED** [review]
Per our discussion today, we should make a 21.7 FB to test these changes. You're planning to open that and tag me for review.

**Comment by labkey-jeckels** [comment]
Per our discussion today

**Pull request closed without merging**
