### PR TITLE
Meds validation

### PR DESCRIPTION
**Pull request by kollil**
Added validation to check volume and amount units if volume and amount data is entered while entering meds.

### CODE REVIEW

**Review by Ohsudev — APPROVED** [review]

**Comment by kollil** [comment]
@labkey-tchad , I made the changes to the code and it's still complaining about missing fields. At this point, I have no other options to try,
Here is the function I added. I added two fields "vol_units" and "amount_units" and put "null" for the data values. Let me know what is missing this time. And, I cannot make any changes to the actual API as it's part of EHR core.

        //Added more validation code, Kollil Dec, 2023
        getApiHelper().testValidationMessage(DATA_ADMIN.getEmail(), "study", "drug", new String[]{"Id", "date", "code", "outcome", "remark", "amount", "amount_units", "volume", "vol_units", "QCStateLabel", "objectid", "_recordId"}, new Object[][]{
                {MORE_ANIMAL_IDS[0], new Date(), "code", "Normal", null, null, null, null, null, EHRQCState.COMPLETED.label, generateGUID(), "recordID"}
        }, Maps.of(
                "amount_units", Arrays.asList( //added these fields by kollil, Nov 30th
                        "WARN: Must enter amount_units if amount is entered"
                ),
                "vol_units", Arrays.asList(
                        "WARN: Must enter volume_units if volume is entered"
                )
        ));


Thanks
Lakshmi

**Comment by labkey-tchad** [comment]
The current failure is happening before your new test case. It looks like some of the existing test cases inadvertently exercise the new validation in that script.
```
java.lang.AssertionError: Incorrect fields have errors. expected:<[remark, _validateOnly]> but was:<[remark, amount_units, vol_units, _validateOnly]>
  at org.junit.Assert.fail(Assert.java:89)
  at org.junit.Assert.failNotEquals(Assert.java:835)
  at org.junit.Assert.assertEquals(Assert.java:120)
  at org.labkey.test.util.ehr.EHRClientAPIHelper.testValidationMessage(EHRClientAPIHelper.java:496)
  at org.labkey.test.util.ehr.EHRClientAPIHelper.testValidationMessage(EHRClientAPIHelper.java:475)
  at org.labkey.test.tests.onprc_ehr.ONPRC_EHRTest.testDrugApi(ONPRC_EHRTest.java:402)
```

**Comment by labkey-martyp** [comment]
Units added to the test data per the added validation in this PR.

**Comment by kollil** [comment]
Thanks @labkey-martyp.

**Pull request merged**
