### PR TITLE
20.11 fb update route medication defition

### PR DESCRIPTION
**Pull request by jonesgaohsu**
O missed the step again to change it from Dev  not sure what step to change it
#### Rationale
Update was not looking up route for medication,. created a medicationFeeDegfinition.query.xml to properly create lookup
#### Related Pull Requests
* 

#### Changes 
Created new xml for medication fee definition reference labkey issue ticket 42108

### CODE REVIEW

**Review by labkey-jeckels — APPROVED** [review]

**Comment by labkey-jeckels** [comment]
@jonesgaohsu this change looks good now. Once you've validated the feature branch build on the test server, please come here to the pull request in GitHub and click the "Squash and merge" button

**Comment by jonesgaohsu** [comment]
Finish process to production instance of 20.11

**Comment by labkey-jeckels** [comment]
@jonesgaohsu it looks like you closed this pull request without merging it. I'm reopening. Please use the "Squash and merge" button like I mentioned, not the "Close" button.

**Comment by jonesgaohsu** [comment]
Attempting to merge a 2nd time, seems I may have clicked the wrong button

**Comment by jonesgaohsu** [comment]
Thanks, still learning the process, Looks like I may be correct now in the process


Gary Jones
Business Analyst 3
Oregon National Primate Research Center
Beaverton Oregon 97006

Office 503-346-5556
Cell 971-998-7909

**Comment by labkey-jeckels** [comment]
Looks good now. Congrats on a successful GitHub merge!

**Comment by jonesgaohsu** [comment]
And away we go

Gary Jones
Business Analyst 3
Oregon National Primate Research Center
Beaverton Oregon 97006

Office 503-346-5556
Cell 971-998-7909

**Pull request merged**
