### PR TITLE
20.11 fb update scheduler test instance

### PR DESCRIPTION
**Pull request by jonesgaohsu**
#### Related Pull Requests
* 

#### Changes
*

### CODE REVIEW

**Comment by labkey-jeckels** [comment]
@jonesgaohsu How does this relate to the other pull request you opened this morning? Most of the changes are the same so the comments would apply to either copy.

https://github.com/LabKey/onprcEHRModules/pull/152

**Comment by jonesgaohsu** [comment]
It looks like I have another Feature Branch that included more than was intended
I was trying to add the extschedule script and the module update

**Comment by jonesgaohsu** [comment]
How do I remove unwanted files in teh FB

**Comment by jonesgaohsu** [comment]
Closing to remove test deployments will create new FB to update for Covid 19

**Pull request closed without merging**
