### PR TITLE
20.11 fb sla email

### PR DESCRIPTION
**Pull request by kollil**
#### Related Pull Requests
Updated SLA email notification

#### Changes
Added new field "Expected Arrival date" to the email notification

### CODE REVIEW

**Comment by kollil** [comment]
Changed to the correct base,  release20.11_snapshot

**Comment by kollil** [comment]
I have tested the functionality in test and uat, the changes are working fine. Please approve the changes to merge into production.
And, I have noticed my previous commit has been added to this one, couldn't figure out how it got added. I have only one updated file in this update, server/modules/onprcEHRModules/sla/src/org/labkey/sla/SLAController.java. Please remove the other file from this commit and approve only the SLA changes.

Thanks
Lakshmi

**Review by labkey-jeckels — APPROVED** [review]
This change looks OK to merge.

As I requested in the last pull request, going forward please use the Reviewers feature in GitHub to let us know when it's ready for a review.

This feature branch looks like it was created from the previous feature branch instead of switching back to the release20.11-SNAPSHOT branch and pulling the latest changes, as described by the third and fourth steps here:

https://www.labkey.org/ONPRC/wiki-page.view?name=DevProcess

That's why you're seeing two changes instead of just the one you expect. It will be fine when it merges as the first set of changes are already in the target branch.

**Comment by kollil** [comment]
Thank you Josh.
I remember you asked me to pick the reviewer last time, but I didn't find a way to pick the reviewer on this page. It was my mistake, was looking in the approval and changes sections and couldn't find it.  I see it now on the right side nav. Will do it from next time. Sorry about that.

**Comment by labkey-jeckels** [comment]
No worries, Lakshmi. I know it's a lot of new process to learn. I'll keep helping aligning things with the preferred workflow, but the important thing is that you're able to get changes into production via GitHub.

**Pull request merged**
